/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.byronpar.ui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.byronpar.TDA.ListaSimpleServicio;
import org.byronpar.TDA.PilaRepuesto;

/**
 *
 * @author HP ENVY
 */
public class Servicioui extends javax.swing.JFrame {

    /**
     * Creates new form Servicioui
     */
    ListaSimpleServicio l = ListaSimpleServicio.getInstancia();
    PilaRepuesto pilaTodo = PilaRepuesto.getInstancia();

    JFileChooser selec = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    CargaMasiva_Servicio datosServicios = new CargaMasiva_Servicio();

    public Servicioui() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLayout(null);
        l.LimpiarTabla(jTable1);
        l.pintarTabla(jTable1);
    }

    public String Abrirxd(File archivo) {
        String documento = "";
        try {
            entrada = new FileInputStream(archivo);

            int algo;
            while ((algo = entrada.read()) != -1) {

                char caracter = (char) algo;
                documento += caracter;

            }
        } catch (Exception e) {

        }
        return documento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtMarca = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TxtManoObra = new javax.swing.JTextField();
        TxtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtListaRep = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre Servicio:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Marca:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 30));
        getContentPane().add(TxtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 140, 30));
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Modelo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 60, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>Precio mano<p>de obra:</p></html>");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 80, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Id Servicio", "Nombre Servicio", "Marca", "Modelo", "Precio Mano de Obra", "Precio Total", "Lista de Repuesto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 870, 270));

        TxtManoObra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtManoObraKeyTyped(evt);
            }
        });
        getContentPane().add(TxtManoObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 140, 30));
        getContentPane().add(TxtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Servicios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html>Lista de <p>Repuestos (Solo id separados por \"  ;  \") : </p></html>");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 70, 90));

        TxtListaRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtListaRepActionPerformed(evt);
            }
        });
        TxtListaRep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtListaRepKeyTyped(evt);
            }
        });
        getContentPane().add(TxtListaRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 140, 30));

        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 138, -1));

        jButton4.setText("Carga Archivo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 138, -1));

        jButton3.setText("Eliminar ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 138, -1));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 138, -1));

        jButton7.setText("Agregar ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/byronpar/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtManoObraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtManoObraKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtManoObraKeyTyped

    private void TxtListaRepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtListaRepKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_TxtListaRepKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Admin entrar = new Admin();
        entrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("tms", "tms");
        selec.setFileFilter(filtro);

        if (selec.showDialog(null, "abrir") == JFileChooser.APPROVE_OPTION) {
            archivo = selec.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("tms")) {
                    String documento = Abrirxd(archivo);
                    datosServicios.area.setText(documento);
                    datosServicios.launchFrame();
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Archivo No Compatible");
                }

            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        
        int FilaSeleccionada = jTable1.getSelectedRow();
        if (FilaSeleccionada != -1) {
            try {
                String indice = "" + jTable1.getValueAt(FilaSeleccionada, 0);
                int  id2 = Integer.parseInt(indice);
                int id3 = id2-1;
               if (l.eliminarEnIndice(id3)) {
                JOptionPane.showMessageDialog(null, "Servicio Eliminado!!");
              l.LimpiarTabla(jTable1);
                l.pintarTabla(jTable1);
            } else {
                
            }
//
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR ");
//
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar Una Fila Para Poder Modificarla");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int FilaSeleccionada = jTable1.getSelectedRow();
        if (FilaSeleccionada != -1) {
            try {
                String indice = "" + jTable1.getValueAt(FilaSeleccionada, 0);
                String id=""+jTable1.getValueAt(FilaSeleccionada, 1);
                String nombre=""+jTable1.getValueAt(FilaSeleccionada, 2);
                
                
                int  indice2 = Integer.parseInt(indice);
                int id3 = Integer.parseInt(id);
                
                String nombrenuevo=TxtNombre.getText();
                String modelonuevo=TxtModelo.getText();
                String listaRepnuevo=TxtListaRep.getText();
                String marcanuevo=TxtMarca.getText();
                Float precioManoNuevo=Float.parseFloat(TxtManoObra.getText());
                
                String [] a= listaRepnuevo.split(";");
                
                
               if (l.ModificarServicio(indice2,id3,nombre,nombrenuevo,modelonuevo,a,marcanuevo,precioManoNuevo)) {
                JOptionPane.showMessageDialog(null, "Servicio Modificado!!");
              l.LimpiarTabla(jTable1);
                l.pintarTabla(jTable1);
            } else {
                
            }
//
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR ");
//
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar Una Fila Para Poder Modificarla");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        // AGREGO A LA LISTA SIMPLE
        if (!"".equals(TxtNombre.getText().trim()) && !"".equals(TxtManoObra.getText().trim())) {
            if (TxtNombre.getText().equalsIgnoreCase("Diagnostico")) {

                String nombre = TxtNombre.getText();
                String manoDeObra1 = TxtManoObra.getText();
                String[] cadenas = {"a"};
                float manoDeObra = Float.parseFloat(manoDeObra1);
                if (this.l.agregarEnIndice(0, nombre, "", "", manoDeObra, cadenas)) {
                    JOptionPane.showMessageDialog(null, "Servicio Agregado Correctamente!!");
                   TxtNombre.setText("");
                TxtManoObra.setText("");
                TxtMarca.setText("");
                TxtModelo.setText("");
                TxtListaRep.setText("");
                } else {

                }

                l.LimpiarTabla(jTable1);
                l.pintarTabla(jTable1);
                

            } else {
                if (!"".equals(TxtNombre.getText().trim()) && !"".equals(TxtManoObra.getText().trim())
                        && !"".equals(TxtMarca.getText()) && !"".equals(TxtModelo.getText()) && !"".equals(TxtListaRep.getText())) {
                    try {

                        // TOMO LA INFORMACIÓN
                        int indice = 0;
                        String nombre = TxtNombre.getText();
                        String marca = TxtMarca.getText();
                        String modelo = TxtModelo.getText();
                        String manoDeObra1 = TxtManoObra.getText();
                        float manoDeObra = Float.parseFloat(manoDeObra1);
                        String repuesto = TxtListaRep.getText();
                        String[] cadenas = repuesto.split(";");

                        if (this.l.agregarEnIndice(indice, nombre, marca, modelo, manoDeObra, cadenas)) {
                            JOptionPane.showMessageDialog(null, "Servicio Agregado Correctamente!!");
TxtNombre.setText("");
                TxtManoObra.setText("");
                TxtMarca.setText("");
                TxtModelo.setText("");
                TxtListaRep.setText("");
                        } else {

                        }

                        l.LimpiarTabla(jTable1);
                        l.pintarTabla(jTable1);
                        
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "ERROR EN DATOS DE REPUESTOS");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "ERROR NO PUEDE DEJAR CAMPOS VACIOS");
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR NO PUEDE DEJAR CAMPOS VACIOS");
        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void TxtListaRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtListaRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtListaRepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicioui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicioui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicioui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicioui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicioui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtListaRep;
    private javax.swing.JTextField TxtManoObra;
    private javax.swing.JTextField TxtMarca;
    private javax.swing.JTextField TxtModelo;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
